### ISSUE TITLE
Expose FlightCallOptions in InfluxDBClient3 constructor

### ISSUE THREAD

**Issue by davide-t-tobe** [InfluxCommunity/influxdb3-python#36]
We're having some random issues while querying data from an InfluxDB Cloud Serverless instance (Version 2.0.0).

The exception logged is the following:
`FlightUnavailableError: Flight returned unavailable error, with message: Received http2 header with status: 504`

We observed this kind of exception almost once about 20 queries, on average (while testing the same query).

FlightClient seems to be configured with a default timeout of 60s. In order to try to overcome this issue, we would like to customize the timeout of do_get method, and implement a retry policy. In the current version of this library, however, FlightCallOptions are static initialized inside the constructor, as seen in this line:
https://github.com/InfluxCommunity/influxdb3-python/blob/38e9fcb63102d08d1748266fd57b1f079bc32c8a/influxdb_client_3/__init__.py#L67

Is there an alternative way to handle this kind of exception?

**Comment by Jayclifford345** [comment]
Hi @davide-t-tobe,
Many thanks for your feedback and great suggestion! Let me work on this it shouldn't take me too long to get you a release. My thoughts are to move this line down into query function and allow expose the FlightCallOptions there

**Comment by Jayclifford345** [comment]
Hi @davide-t-tobe,
Just added this feature and cut a release; checkout `version 0.1.9`
Here is an example: https://github.com/InfluxCommunity/influxdb3-python/blob/main/Examples/pokemon-trainer/write-batching-flight-calloptions.py
