### ISSUE TITLE
`pandas` is imported but it is not marked as a dependency

### ISSUE THREAD

**Issue by Bo98** [InfluxCommunity/influxdb3-python#41]
It is imported unconditionally here:

https://github.com/InfluxCommunity/influxdb3-python/blob/9824b944c708f2b830f6ed3d880f9171c857f603/influxdb_client_3/read_file.py#L5

Since it's only used in one place, it could be made an optional dependency by moving it into the `load_json`. `pandas` is an optional dependency in both `pyarrow` and `influxdb-client` (v2).

Otherwise, the alternative would be to make it mandatory dependency:

https://github.com/InfluxCommunity/influxdb3-python/blob/9824b944c708f2b830f6ed3d880f9171c857f603/setup.py#L39

**Comment by Bo98** [comment]
It would also help with the particularly slow import times:

<img width="1040" alt="Screenshot 2023-07-23 at 22 06 56" src="https://github.com/InfluxCommunity/influxdb3-python/assets/1190754/6203e1e3-b6b6-46bc-952b-a203108e6c57">

**Comment by Jayclifford345** [comment]
Hi @Bo98,
Many thanks for the suggestion! This was my oversite. To keep the Client slim I have included it as an optional dependency and included some error handling for utilities which require pandas. Such as the [write_file()](url)
