### ISSUE TITLE
InfluxDB Cloud Serverless - Query results in mysterious exception 

### ISSUE THREAD

**Issue by ViktorIngemarsson** [InfluxCommunity/influxdb3-python#47]
Executing query with "group by"-clause leads to mysterious exception not debuggable user. The exception that is thrown is as seen below. The query is a rather "complex" one but it fails dependent on the data that it hits but succeeds for some filtering options. I have a setup where all measurements has explicit schema and all has the same tags defined. Reach out if you need help recreating the issue coz it is consistent. 

SELECT LAST(*) FROM “measurement1”, “measurement2”, “measurement3” WHERE time >= ‘2023-07-22 13:53:14’ AND time <= ‘2023-07-22 14:15:53’ AND “organization” = ‘ssrs’ AND “some_id” = ‘0ce620c2-dcab-4521-a3c4-f6352da54cfa’ GROUP BY “tag1”, “measurement”, “ tag2”, “ tag3”, “ tag4”, time(10s) fill(none)

/.venv/lib/python3.10/site-packages/influxdb_client_3/init.py", line 153, in query
return mode_func() if callable(mode_func) else mode_func
File “pyarrow/_flight.pyx”, line 1070, in pyarrow._flight.FlightStreamReader.read_all
File “pyarrow/_flight.pyx”, line 1073, in pyarrow._flight.FlightStreamReader.read_all
File “pyarrow/_flight.pyx”, line 55, in pyarrow._flight.check_flight_status
pyarrow._flight.FlightInternalError: Flight returned internal error, with message: stream terminated by RST_STREAM with error code: NO_ERROR. gRPC client debug context: UNKNOWN:Error received from peer ipv4:3.123.149.45:443 {created_time:“2023-07-26T14:12:44.992317+02:00”, grpc_status:13, grpc_message:“stream terminated by RST_STREAM with error code: NO_ERROR”}. Client context: OK

**Comment by Jayclifford345** [comment]
Hi @ViktorIngemarsson, many thanks for opening an issue and using the library.

Hmm this is interesting; so I assume based on your query its using InfluxQL as the query language. Would you mind letting me know how many columns and data samples this is expected to return? Knowing how many columns is in each measurement I think would be a good place to start as I am wondering if we are hitting limits with this query on the server side.

**Comment by ViktorIngemarsson** [comment]
The columns would be the grouped by tags, which is 5, together with time and two value columns, a total of 8 columns.
The number of rows would be in the thousands but < 10'000.
It should not be due to the number of columns since depending on what grouping tag I remove from the query it returns a result even though the total number of columns would be constant. I have identified a tag which if included in the query it fails and if not included the query succeeds. Reach out if you wanna take a meeting and I can show you exactly what is happening but I can't debug anymore since the errors are on the server side.

**Comment by Jayclifford345** [comment]
Hi @ViktorIngemarsson,
Yep let's create a meeting, if you wouldn't mind dropping into our community slack channel I can talk to you there:
https://influxcommunity.slack.com/ssb/redirect

**Comment by Jayclifford345** [comment]
Hi @ViktorIngemarsson, I know its been a long long time for this grouping issue to be solved. Would you mind taking another run of your queries as we have solved a few server-side performance issues in this area.

**Comment by ViktorIngemarsson** [comment]
I have worked around the issue in the backend but I see that you have
solved other server side issues in the last few weeks.
Queries that intermittently has been throwing errors are now since ~2weeks
back working fine.
Unfortunately I don't know which query this was referencing, I am sorry.

Den mån 6 nov. 2023 kl 11:09 skrev Jay Clifford ***@***.***>:

**Comment by ViktorIngemarsson** [comment]
I don't have this exact problem anymore since I have worked around it. 
Since ~2 weeks ago though other queries that has been throwing exceptions intermittently does not anymore. Good work, thanks.

**Comment by nhimxu00** [comment]
it is my code run:
```
table = client.query(
    query="SELECT * FROM measurement",
    language="influxql")

print("table:")
print(table)

query = "SELECT * FROM test WHERE time >= -90d"
table = client.query(query=query, language="all")
# Filter columns.
print(table.select(['room', 'temp']))
```

but i have error:
`FlightUnavailableError: Flight returned unavailable error, with message: DNS resolution failed for https:: C-ares status is not ARES_SUCCESS qtype=A name=https is_balancer=0: Could not contact DNS servers. gRPC client debug context: UNKNOWN:DNS resolution failed for https:: C-ares status is not ARES_SUCCESS qtype=A name=https is_balancer=0: Could not contact DNS servers {grpc_status:14, created_time:"2023-11-15T11:31:17.497915414+07:00"}. Client context: IOError: Server never sent a data message. Detail: Internal`
