### ISSUE TITLE
Mode on query not working

### ISSUE THREAD

**Issue by Anaisdg** [InfluxCommunity/influxdb3-python#66]
I'm getting the following error with this query:
```
TypeError: InfluxDBClient3.query() got an unexpected keyword argument 'mode'
```
```
from influxdb_client_3 import InfluxDBClient3
import pandas as pd

client = InfluxDBClient3(token="",
                         host="us-east-1-1.aws.cloud2.influxdata.com",
                         database="demo")
query = "SELECT * FROM cpu WHERE time >= now() - INTERVAL '30 days'"
pd = client.query(query=query, mode='pandas')
````
Am I missing something? 
I think this was working for me previously.

**Comment by Jayclifford345** [comment]
Hi @Anaisdg,
hmm, this should still be working fine. Can you check what version you have installed?
Here is my test using the latest with mage.ai 
<img width="1051" alt="Screenshot 2023-10-05 at 09 34 54" src="https://github.com/InfluxCommunity/influxdb3-python/assets/45856600/4084e753-07ed-4bba-a358-0229b07f101e">

**Comment by Anaisdg** [comment]
Yah I've been using it. Well its working now, so I don't know what was happening. Thank you!
