### ISSUE TITLE
pandas isn't optional due to incorrect import

### ISSUE THREAD

**Issue by salty-horse** [InfluxCommunity/influxdb3-python#69]
The top of `__init__.py` file has an import for `UploadFile`, which requires `pandas`.

I think the intent is for the import to be inside the `write_file` function, so `pandas` would only be required if you call that function.

**Comment by Jayclifford345** [comment]
Hi @salty-horse, thank you for bringing this to my attention and sorry for the late reply. I will work on a fix for this.
