### ISSUE TITLE
Query Error: FlightUnavailableError: "Cannot check peer: missing selected ALPN property.. gRPC client debug context"

### ISSUE THREAD

**Issue by nikfio** [InfluxCommunity/influxdb3-python#71]
Hi guys,

I am happily using the new influxdb3 python client with a influxdb cloud serverless instance.
When I am working with my company pc running windows 10 I get this error during a query attempt:

`FlightUnavailableError: Flight returned unavailable error, with message: failed to connect to all addresses; last error: UNKNOWN: ipv4:3.123.149.45:443: Cannot check peer: missing selected ALPN property.. gRPC client debug context: UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:3.123.149.45:443: Cannot check peer: missing selected ALPN property. {grpc_status:14, created_time:"2023-12-12T12:29:11.635384065+00:00"}. Client context: IOError: Server never sent a data message. Detail: Internal`

Here is how it is implemented the InfluxDBClient3:

            ```
            add_kwargs['verify_ssl'] = self.ssl_certificate
            fh = open(self.ssl_certificate, "r")
            cert_file = fh.read()
            fh.close()
            
            add_kwargs['ssl_ca_cert'] = cert_file
       
            add_kwargs['verify_ssl'] = True
           
            add_kwargs['proxy'] = self.proxies['https_proxy']
            
        
        
            client = InfluxDBClient3( host=self.url,
                                  token=self.token,
                                  database=bucket,
                                  write_client_options  = None,
                                  flight_client_options = flight_client_options(
                                                          tls_root_certs=cert_file),
                                  **add_kwargs )
            ```

Here is the closest and most recent discussion I found : https://github.com/grpc/grpc/issues/23172 
but I can't tell how to make it work through our influxdb3 client.

Most likely, I think this has something to do with the windows pc running behind company proxy.
Even though I try to set the proxy as added argument, the error keeps getting out.

Meanwhile, running the client from an external pc or even a AWS EC2 ubuntu, the query does the job smoothly, no errors.

Do you have any suggestion? 
Any help or any question is appreciated.

Nick

**Comment by Jayclifford345** [comment]
Hi Nick,
I hope you are doing well. Before we jump straight into the proxy issue could we sense check the certificate with the certif method which we have tested against Windows:
```python
import influxdb_client_3 as InfluxDBClient3
import pandas as pd
import numpy as np
from influxdb_client_3 import flight_client_options
import certifi

fh = open(certifi.where(), "r")
cert = fh.read()
fh.close()


client = InfluxDBClient3.InfluxDBClient3(
    token="",
    host="b0c7cce5-8dbc-428e-98c6-7f996fb96467.a.influxdb.io",
    org="6a841c0c08328fb1",
    database="flightdemo",
    flight_client_options=flight_client_options(
        tls_root_certs=cert))


table = client.query(
    query="SELECT * FROM flight WHERE time > now() - 4h",
    language="influxql")

print(table.to_pandas())
```
If this still fails let me know and we can dig further into the issue.

**Comment by Jayclifford345** [comment]
Hi @nikfio,
So this sadly seems to be an issue with the company network. Perhaps you could reach out to your network security administrator. The two main issues I see that are most likely causing the ALPN issue:

- Check if any firewall or security group settings are blocking the gRPC traffic. gRPC typically uses HTTP/2, which might be blocked in your companies network

- Check your TLS certificates support the ALPN extension

**Comment by Jayclifford345** [comment]
Closing as network related issue. Can re-open if further network information is found

**Comment by nikfio** [comment]
> Hi @nikfio, So this sadly seems to be an issue with the company network. Perhaps you could reach out to your network security administrator. The two main issues I see that are most likely causing the ALPN issue:
> 
> * Check if any firewall or security group settings are blocking the gRPC traffic. gRPC typically uses HTTP/2, which might be blocked in your companies network
> * Check your TLS certificates support the ALPN extension

Hello @Jayclifford345,

I confirm I am working behing a proxy "forcing use of HTTP1.1 for encrypted connections", as they told me.

As also noted here [Using Zscaler with http2](https://community.zscaler.com/s/question/0D54u00009evlPgCAI/using-zscaler-with-http2).
I think I am in a very similar situation.

Do you know if there is a way to make gRPC and so our influxdb3 client in HTTP1.1? 
How bad would be the performance downgrade?

I am checking for the ALPN extension of the certificate. I will let you guys know.


Thanks,
NIck
