### ISSUE TITLE
AttributeError: 'pyarrow._flight.FlightClient' object has no attribute 'close'

### ISSUE THREAD

**Issue by alexandnpu** [InfluxCommunity/influxdb3-python#73]
There is exception when closing InfluxDBClient3

see issue title

my version is influxdb3-python==0.2.3

**Comment by Jayclifford345** [comment]
Hi @alexandnpu,
Many thanks for using the Python client! Would you mind showing me how you are closing the client as I might have overlooked a method of closing, Here is how I currently do this:
```python


import polars as pl
from influxdb_client_3 import InfluxDBClient3



client = InfluxDBClient3(
    token="",
    host="eu-central-1-1.aws.cloud2.influxdata.com",
    org="6a841c0c08328fb1")

sql = 'SELECT * FROM caught LIMIT 10'

table = client.query(database="pokemon-codex", query=sql, language='sql', mode='all')

df = pl.from_arrow(table)

print(df)

client.close()

```

Here is the result:
```
(.venv) jayclifford@Jays-MBP Polars % python3 influxdb_query.py 
shape: (10, 12)
┌────────┬─────────┬─────┬──────┬───┬────────────────────────────┬─────────┬───────┬────────┐
│ attack ┆ defense ┆ hp  ┆ id   ┆ … ┆ time                       ┆ trainer ┆ type1 ┆ type2  │
│ ---    ┆ ---     ┆ --- ┆ ---  ┆   ┆ ---                        ┆ ---     ┆ ---   ┆ ---    │
│ i64    ┆ i64     ┆ i64 ┆ str  ┆   ┆ datetime[ns]               ┆ str     ┆ str   ┆ str    │
╞════════╪═════════╪═════╪══════╪═══╪════════════════════════════╪═════════╪═══════╪════════╡
│ 49     ┆ 49      ┆ 45  ┆ 0001 ┆ … ┆ 2023-12-20 11:08:25.209547 ┆ ash     ┆ Grass ┆ Poison │
│ 49     ┆ 49      ┆ 45  ┆ 0001 ┆ … ┆ 2023-12-20 14:36:19.893693 ┆ ash     ┆ Grass ┆ Poison │
│ 49     ┆ 49      ┆ 45  ┆ 0001 ┆ … ┆ 2023-12-20 11:11:25.209547 ┆ ash     ┆ Grass ┆ Poison │
│ 49     ┆ 49      ┆ 45  ┆ 0001 ┆ … ┆ 2023-12-20 14:49:19.893693 ┆ ash     ┆ Grass ┆ Poison │
│ …      ┆ …       ┆ …   ┆ …    ┆ … ┆ …                          ┆ …       ┆ …     ┆ …      │
│ 49     ┆ 49      ┆ 45  ┆ 0001 ┆ … ┆ 2023-12-20 11:16:25.209547 ┆ ash     ┆ Grass ┆ Poison │
│ 49     ┆ 49      ┆ 45  ┆ 0001 ┆ … ┆ 2023-12-20 15:31:19.893693 ┆ ash     ┆ Grass ┆ Poison │
│ 49     ┆ 49      ┆ 45  ┆ 0001 ┆ … ┆ 2023-12-20 11:10:25.209547 ┆ ash     ┆ Grass ┆ Poison │
│ 49     ┆ 49      ┆ 45  ┆ 0001 ┆ … ┆ 2023-12-20 15:15:19.893693 ┆ ash     ┆ Grass ┆ Poison │
```

**Comment by alexandnpu** [comment]
I also pasted my stacktrace here, noticing that I am using python 3.6. 

> Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "write_iox_client.py", line 49, in write_to_iox
    iox_client.write(point)
  File "/path-to-venv/venv/lib64/python3.6/site-packages/influxdb_client_3/__init__.py", line 227, in __exit__
    self.close()
  File "/path-to-venv/venv/lib64/python3.6/site-packages/influxdb_client_3/__init__.py", line 220, in close
    self._flight_client.close()
AttributeError: 'pyarrow._flight.FlightClient' object has no attribute 'close'


below is my code

```
def write_to_iox(data_file):
    print("processing {}".format(data_file))

    with InfluxDBClient3.InfluxDBClient3(host="http://127.0.0.1:18080", enable_gzip=True, org="test", database="xxxx", write_client_options=wco) as iox_client:
        with open(data_file, "r") as f:
            batch_lines = []
            for line in f:
                obj = json.loads(line)
                point = create_iox_point(obj)
                iox_client.write(point)
```

**Comment by Jayclifford345** [comment]
hmm interesting can you try with the latest version?
I will try to reproduce on my end with v0.3.4

**Comment by Jayclifford345** [comment]
I sadly still not reproduce this on the latest build:
<img width="792" alt="Screenshot 2024-01-05 at 13 56 25" src="https://github.com/InfluxCommunity/influxdb3-python/assets/45856600/d5705093-50bc-4a65-b186-54a2e0280335">

**Comment by alexandnpu** [comment]
## Root Cause

I found the root cause!

in my setup, the versions are listed below

```
influxdb-client==1.31.0
influxdb3-python==0.2.3
pyarrow==6.0.1
```

in pyarrow 6.0.1, there is indeed no `close` method for FlightClient. 
It seems that the `close` method is [added in 8.0.0](https://github.com/apache/arrow/commit/647371b504df166860bd33346dcbd962c85e046f),

So, in order to make influxdb3-python `close` work, pyarrow need to be above `8.0.0`.


## python version

I also found another small issue when I tried influxdb3-client v0.3.4. 
As v0.3.4 depends reactive>=4.0.4 and reactive needs python to be at least python 3.7, influxdb3-python should also have this version requirement.
Also, the minimum python version that can be used with pyarrow>=8.0.0 is python 3.7.

So I think influxdb3-python should also update its minimum allowed python version.
Or you can find another solution to make python 3.6 work with influxdb3-python, which for my work environment will be better.

**Comment by Jayclifford345** [comment]
Thank you @alexandnpu, I will create a ticket and get the versions updated
