### ISSUE TITLE
InfluxDBClient3.query() raises pyarrow._flight.FlightUnavailableError

### ISSUE THREAD

**Issue by berendovychRB** [InfluxCommunity/influxdb3-python#81]
### Specifications

* Client Version: influxdb3-python == 0.3.6
* InfluxDB Version: influxdb == 2.7.5
* Platform: Ubuntu 22.04

### Code sample to reproduce problem

```from influxdb_client_3 import InfluxDBClient3, InfluxDBError, WriteOptions, write_client_options

TOKEN = "1YKr6sjDM2GmyOCo9D-MCcpw-ZkSQG4tLg_0CtVFDysl9DCD5k1375B7ns4Ahuy7cme6V1QLrVPROGP-ExHrHw=="
org = "org"
url = "http://localhost:8086"
bucket = "bucket"

class BatchingCallback(object):

    def success(self, conf, data: str):
        print(f"Written batch: {conf}")

    def error(self, conf, data: str, exception: InfluxDBError):
        print(f"Cannot write batch: {conf}, data: {data} due: {exception}")

    def retry(self, conf, data: str, exception: InfluxDBError):
        print(f"Retryable error occurs for batch: {conf}, data: {data} retry: {exception}")

callback = BatchingCallback()

write_options = WriteOptions(batch_size=100,
                                        flush_interval=10_000,
                                        jitter_interval=2_000,
                                        retry_interval=5_000,
                                        max_retries=5,
                                        max_retry_delay=30_000,
                                        exponential_base=2)

wco = write_client_options(success_callback=callback.success,
                          error_callback=callback.error,
                          retry_callback=callback.retry,
                          WriteOptions=write_options
                        )

client = InfluxDBClient3(
    token=TOKEN,
    host=url,
    org=org,
    database=bucket
)

try:
     for value in range(20, 30):
         point = Point("measurement").tag("location", "london").field("temperature", value)

         client.write(record=point)
         time.sleep(1)
except Exception as e:
     print(f"Error writing point: {e}")

query = '''SELECT * FROM measurement'''
table = client.query(query=query, language='sql')




```

### Expected behavior

To retrieve some data

### Actual behavior

The writing in influxdb works correctly, but retrieving raises error

`pyarrow._flight.FlightUnavailableError: Flight returned unavailable error, with message: failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8086: Ssl handshake failed: SSL_ERROR_SSL: error:0A00010B:SSL routines::wrong version number. gRPC client debug context: UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8086: Ssl handshake failed: SSL_ERROR_SSL: error:0A00010B:SSL routines::wrong version number {created_time:"2024-04-05T10:58:40.015658046+03:00", grpc_status:14}. Client context: IOError: Server never sent a data message. Detail: Internal
`

### Additional info

I was trying to write by influxdb_client_3 and read by influxdb_client (version 2), it works, I get data that was written
But with version 3 I cannot do that

**Comment by bednar** [comment]
Hi @berendovychRB,

Thank you for choosing our client for your project. I noticed you're attempting to connect to an InfluxDB 2 instance using the `influxdb3-python` client. This client designed to work with InfluxDB 3, which lead to issues that you see.

To ensure full compatibility and to take advantage of all the features available in InfluxDB 2, please use the official InfluxDB 2 client for Python available here: [influxdb-client-python](https://github.com/influxdata/influxdb-client-python).

For more detailed information about InfluxDB 3 and its features, please visit the following link: [InfluxDB Overview](https://www.influxdata.com/products/influxdb-overview/).

Switching to the appropriate client should resolve any connection or compatibility issues you're experiencing. If you have any further questions or require additional assistance, feel free to reach out.

Best Regards.
