### ISSUE TITLE
Return error on write errors

### ISSUE THREAD

**Issue by powersj** [InfluxCommunity/influxdb3-python#91]
### Specifications

* Client Version: 0.5.0
* InfluxDB Version: serverless
* Platform: linux

### Code sample to reproduce problem

```python
# the second record changes the type of temp to a string
# this should result in a failure due to the schema conflict
records = [
    {
        "measurement": "newcpu",
        "tags": {"newcore": "4"},
        "fields": {"temp": 100.4},
        "time": 1712010258000000000
    },
    {
        "measurement": "newcpu",
        "tags": {"newcore": "4"},
        "fields": {"temp": "25"},
        "time": 17121808720000000
    },
]

with InfluxDBClient3(
    token="secret",
    host="us-east-1-1.aws.cloud2.influxdata.com",
    org="",
    database="test",
) as client:
    print(client.write(record=records, write_precision="ns"))
```

### Expected behavior

An error or exception is returned if an error is encountered.

### Actual behavior
None is always returned.

The callback method, gives a way of printing out errors, but a user should be able to do something to programmatically know if their writes completed without error.

[None is always returned](https://github.com/InfluxCommunity/influxdb3-python/blob/main/influxdb_client_3/write_client/client/write_api.py#L379-L380) unless the write type is asynchronous. If a user is using synchronous writing, then if an error is returned, the user should get the error or exception thrown.

Similarly, if a user is [using batching](https://github.com/InfluxCommunity/influxdb3-python/blob/main/influxdb_client_3/write_client/client/write_api.py#L446-L496) we should be returning an error or throwing an exception.

**Comment by bednar** [comment]
Hi @powersj,

Currently, `None` is returned only for successful sync writes. As an improvement, we could return the entire response from the InfluxDB server. 

> An error or exception is returned if an error is encountered.

The client already correctly exposes exceptions from the InfluxDB server for issues like wrong credentials or invalid LineProtocol ingestion.

For your code, InfluxDB returns HTTP 204 as a response:

```python
from influxdb_client_3 import InfluxDBClient3

records = [
    {
        "measurement": "newcpu",
        "tags": {"newcore": "4"},
        "fields": {"temp": 100.4},
        "time": 1717149615000000000
    },
    {
        "measurement": "newcpu",
        "tags": {"newcore": "4"},
        "fields": {"temp": "25"},
        "time": 17171490000000000
    },
]

token = "my-token"
host = "https://us-east-1-1.aws.cloud2.influxdata.com/"
database = "my-database"

with InfluxDBClient3(token=token, host=host, org="", database=database, debug=True) as client:
    print(client.write(record=records, write_precision="ns"))

```

```console
>>> Request: 'POST https://us-east-1-1.aws.cloud2.influxdata.com:443/api/v2/write?org=&bucket=database&precision=ns'
>>> Content-Type: text/plain
>>> Accept: application/json
>>> Authorization: ***
>>> User-Agent: influxdb-client-python/1.38.0dev0
>>> Body: b'newcpu,newcore=4 temp=100.4 1717149615000000000\nnewcpu,newcore=4 temp="25" 17171490000000000'
<<< Response: 204
<<< Date: Fri, 31 May 2024 10:05:25 GMT
<<< Content-Type: application/json
<<< Connection: keep-alive
<<< trace-id: 38c4a149e6d65508
<<< trace-sampled: false
<<< Strict-Transport-Security: max-age=31536000; includeSubDomains
<<< X-Influxdb-Request-ID: 004201da8362a3a4d9c08c632cff31f5
<<< X-Influxdb-Build: Cloud
<<< Body: 
None
```

> the second record changes the type of temp to a string
> this should result in a failure due to the schema conflict

It appears to be an issue on the InfluxDB server side.

Best Regards

**Comment by powersj** [comment]
> Currently, None is returned only for successful sync writes

And otherwise, an exception is thrown for any error? Does that include any 4xx or 5xx return code?

I'll follow up internally about the 200 on a schema conflict.

**Comment by bednar** [comment]
> And otherwise, an exception is thrown for any error?  Does that include any 4xx or 5xx return code?

Yes, the synchronous client will throw an exception for any kind of error, including any 4xx or 5xx return codes.

**Comment by powersj** [comment]
Alright, then it sounds like there is nothing to do here for the client. I'll close this. Thanks again for clarifying the behavior.
