### ISSUE TITLE
Unable to query Influx cloud serverless

### ISSUE THREAD

**Issue by AdrianSkib** [InfluxCommunity/influxdb3-python#96]
Trying to execute a simple query ( that I've printed, and successfully ran in both Grafana and Influx Data Explorer )
I get

```
E0619 17:07:33.884000000 38728 hpack_parser.cc:1218] Error parsing metadata: error=invalid value key=content-type value=text/html
Traceback (most recent call last):
  File "c:\Users\AdrianSkibelid\Documents\code\path_planning\tmp.py", line 51, in <module>
    table = client.query(query=query, database="numerical-downsampled", language='sql')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AdrianSkibelid\Documents\code\path_planning\.venv\Lib\site-packages\influxdb_client_3\__init__.py", line 284, in query
    raise e
  File "C:\Users\AdrianSkibelid\Documents\code\path_planning\.venv\Lib\site-packages\influxdb_client_3\__init__.py", line 270, in query
    flight_reader = self._flight_client.do_get(ticket, _options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\\_flight.pyx", line 1633, in pyarrow._flight.FlightClient.do_get
  File "pyarrow\\_flight.pyx", line 58, in pyarrow._flight.check_flight_status
pyarrow._flight.FlightServerError: Flight RPC failed with message: Received http2 header with status: 405. gRPC client debug context: UNKNOWN:Received http2 header with status: 405 {grpc_status:2}. Client context: IOError: Server never sent a data message. Detail: Internal
```

Code:

```
from datetime import datetime
import certifi
import math
from influxdb_client_3 import InfluxDBClient3, flight_client_options

fh = open(certifi.where(), "r")
cert = fh.read()
fh.close()

start = (datetime.fromisoformat("2024-05-15T06:53:19.042Z")).replace(second=0, microsecond=0)
stop = (datetime.fromisoformat("2024-05-15T10:53:19.042Z")).replace(second=0, microsecond=0)
token = REDACTED
org = "Prod"
host = "https://westeurope-1.azure.cloud2.influxdata.com"
client = InfluxDBClient3(host=host, token=token, org=org, flight_client_options=flight_client_options(tls_root_certs=cert))
start_timestamp = math.floor(start.timestamp())
stop_timestamp = math.floor(stop.timestamp())
query = f"""from(bucket: "numerical-downsampled")
    |> range(start: {start_timestamp}, stop: {stop_timestamp})
    |> filter(fn: (r) => r._measurement == "ROV_status/OPC_NUC/Latitude")"""
table = client.query(query=query, database="numerical-downsampled", language='sql')
```

The token I'm using has read access to the bucket "numerical-downsampled".

I'm using influxdb3-python==0.5.0

Please advice!

**Comment by bednar** [comment]
Hi @AdrianSkib,

Thank you for using our client. This client is designed for use with InfluxDB 3. If you need to query InfluxDB 2, please use the [InfluxDB 2 client](https://github.com/influxdata/influxdb-client-python).

Best regards

**Comment by AdrianSkib** [comment]
Hi, this issue occurs while I'm querying towards influx cloud serverless running InfluxDB 3.

**Comment by bednar** [comment]
Hi @AdrianSkib,

Sorry for the confusion. It appears that the issue might be related to your query. You're using FluxQL, but InfluxDB 3 only supports SQL and InfluxQL. For more information, please see [InfluxDB 3 Python Client README](https://github.com/InfluxCommunity/influxdb3-python?tab=readme-ov-file#querying).

Best regards

**Comment by AdrianSkib** [comment]
Hi,

Thanks for your suggestion.

I've also tried SQL, but got the same result. Any other ideas for what might be wrong?

Best regards

**Comment by bednar** [comment]
Could you please try specifying the correct SQL and host, such as `host="westeurope-1.azure.cloud2.influxdata.com"`?

**Comment by AdrianSkib** [comment]
```
from datetime import datetime
import certifi
import os
import math
from influxdb_client_3 import InfluxDBClient3, flight_client_options

fh = open(certifi.where(), "r")
cert = fh.read()
fh.close()

token = os.getenv("INFLUX_READ_TOKEN")
org = "Prod"
org = "53337765eee30b18"
host = "westeurope-1.azure.cloud2.influxdata.com"

client = InfluxDBClient3(
    host=host,
    token=token,
    org=org,
    flight_client_options=flight_client_options(tls_root_certs=cert),
)

query = """SELECT *
FROM 'ROV_status/OPC_NUC/Latitude'
WHERE time >= now() - interval '24 hours'"""

table = client.query(query=query, database="numerical-downsampled", language="sql")
```

**Comment by bednar** [comment]
>  """SELECT *
FROM 'ROV_status/OPC_NUC/Latitude'
WHERE time >= now() - interval '24 hours'"""


It appears you meant to use `influxql`, not `sql`.

Could you please provide a complete, runnable example including data ingestion? It would greatly assist us in troubleshooting your issue effectively.

**Comment by AdrianSkib** [comment]
Yes, sry. But I get the same error when I specify language="influxql". I'll see what I can do about example with data ingestion as well...  But it seems to be something weird regardless of the query and data in the db.

**Comment by AdrianSkib** [comment]
Nevermind, I had misunderstood; the serverless instance is in fact running Influxdb 2. Sorry for wasting your time.

**Comment by bednar** [comment]
It’s ok, feel free to contact us with any questions.
